# 2.0.1 segment_dur=2
# 2.0.2 n_layers=8
# 2.0.3 d_model=1024
# 2.0.4 all_above
# 3.0.1 output Residual Connections, segments_dur = 2
# 4.0.1 output RNN, segments_dur = 2
# 5.0.1 split
# 6.0.1 delayed 1 step

version: '6.0.1'
segment_dur: 2
frame_dim: 320
batch_size: 256
model_mode: delayed #parallel, delayed
num_workers: 8

dir_ckp: meta/checkpoint
speech_dataset: dataset/vctk.csv
environment_dataset: dataset/fsd50k.csv
music_dataset: dataset/jamendo.csv
plc_challenge_path: meta/plc_challenge_2024_val_subsample.csv

tests_dir: tests

codec:
  sample_rate: 24000
  codebook_size: 1024
  kbps: 6.0

transformer:
  d_model: 512
  d_attn: 512
  n_heads: 8
  n_layers: 4
  dropout: 0.1
  dropout_attn: 0.0
  special_token: 1025
