version: '1.0.0'

segment_dur: 2 # seconds, more gives problem with the dataset
device: cuda:0
frame_dim: 320

batch_size: 64
n_epochs: 400
steps_per_epoch: 250
learning_rate: 0.0001
num_workers: 8
resume: false
save: true
epoch_to_save: 25

ckpt_path: meta/checkpoint
speech_dataset: dataset/vctk.csv
environment_dataset: dataset/fsd50k.csv
music_dataset: dataset/jamendo.csv
plc_challenge_path: meta/plc_challenge_2024_val_subsample.csv

tests_dir: tests

codec:
  sample_rate: 24000
  n_codebooks: 4
  codebook_size: 1024
  bitrate: 3.0

transformer:
  d_model: 512
  d_attn: 512
  n_heads: 8
  n_layers: 4
  dropout: 0.1
  dropout_attn: 0.0
