version: '2.0.0'
batch_size: 64
n_epochs: 50
steps_per_epoch: 500
learning_rate: 0.001
sample_rate: 48000
packet_dim: 320
segment_dur: 2 # seconds, more gives problem with the dataset
num_workers: 8
resume: false
save: true
epoch_to_save: 5

training_metadata_path: meta/training.csv
validation_metadata_path: meta/validation.csv
test_metadata_path: meta/test.csv
plc_challenge_path: meta/plc_challenge_2024_val_subsample.csv
tests_dir: tests

codec:
  n_codebooks: 8
  codebook_size: 1024
  model_bitrate: 8kbps
  device: cuda:1

transformer:
  d_model: 512
  d_attn: 512
  n_heads: 8
  n_layers: 4
  dropout: 0.1
  dropout_attn: 0.0
  device: cuda:1
